language: rust
rust:
  - stable
  - beta
  - nightly

script:
  - cargo build --verbose --features=cli
  - cargo test --verbose --features=cli

cache: cargo

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

after_success: |
  [ $TRAVIS_BRANCH = main ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc &&
  echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`/index.html>" > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages